### ISSUE TITLE
Add ability to specify classes on admin inline fields (to collapse)

### ISSUE THREAD

**Issue by olivierdalang** [theatlantic/django-nested-admin#52] opened 2016-08-10 22:56 UTC
Hi !

This commit https://github.com/django/django/commit/5399ccc0f4257676981ef7937ea84be36f7058a6 (applied to Django 1.10) allows to collapse inlines exactly like regular formsets, just by adding `classes=['collapse']` in the Inline class.

As nested inlines can be even longer than regular inlines, it would be really nice to have this feature in django-nested-admin too.

I tried to make it work (patched django with the commit above, and made the same changes to nested-admin's stacked and tabular templates). It's almost ok, but it breaks the ability to order the rows by drag&drop for tabular inlines nested in stacked inlines.

Thanks for the great work

**Comment by fdintino** [comment] 2016-08-11 00:50
You shouldn't need to make any changes to django-nested-admin, it should already have support for defining `classes` on the inline. But you may need to backport the css and javascript changes to get collapsing to work correctly. Alternatively you could use django-grappelli, which will give you collapsible inlines with Django < 1.10. That's what we do at The Atlantic and it works well.

**Comment by fdintino** [comment] 2016-08-11 00:52
Oh, what you might be running into: between Django 1.10 alpha and Django 1.10 beta they upgraded the version of jQuery UI bundled with Django, and that broke the drag-and-drop sorting. I have fixing that on my to-do list, but if you selectively avoid backporting the jQuery UI upgrade then drag-and-drop should still work.

**Comment by olivierdalang** [comment] 2016-08-11 13:22
Hi, thanks for the quick answer !

I used grappelli at the begining of my project, but since django 1.9 came out with the improved admin, in an effort to reduce third party packages dependency and to have better control on the display on mobile devices, I decided to switch back to stock admin.

You're right that the classes already appear, bur for collapsing to work in vanilla admin, the DOM has to look like this :
```
<fieldset class="collapse">
   <h2>title</h2>
   .... [content that should be folded] ...
</fieldset>
```

There is already a <fieldset> in django nested's TabularInline, so it's just a matter of moving the classes there.
There is no <fieldset> in django nested's StackedInline, so it would have to be added.

Those two changes are exactly those made in https://github.com/django/django/commit/5399ccc0f4257676981ef7937ea84be36f7058a6

As I said, they work very well, and with those, the nested inlines are collapsible.
The only problem is that it breaks drag&drop. I think it has to do with ' > ' in the selectors used in the javascript managing the drag&drop. But I'm relatively ignorant when it comes to javascript and couldn't sort it out.

**Comment by fdintino** [comment] 2016-08-11 13:44
Oh! I didn't notice that they added an extra wrapping `<fieldset>` with that change. That's almost certainly the cause of the issue, and it would be relatively easy for me to fix. I'll take a stab at it today or tomorrow.

**Comment by olivierdalang** [comment] 2016-08-12 12:28
Awesome, thanks for the great support ! I'll be happy to help testing !!

Coming back here today I just saw there's already PR https://github.com/theatlantic/django-nested-admin/pull/32 open for exactly that (but only for tabular nested inlines)

**Comment by fdintino** [comment] 2016-09-10 03:54
@olivierdalang Could you test out the [dj110-inline-classes](https://github.com/theatlantic/django-nested-admin/compare/dj110-inline-classes) branch? I'd like to write some unit tests, but if what I have is working I wouldn't want that to hold up getting this on master.

**Comment by fdintino** [comment] 2016-09-13 05:07
I've written a unit test and merged this into master.

**Closed by fdintino** 2016-09-13 05:07 UTC
