### ISSUE TITLE
MediaOrderConflictWarning adding new inline with date widget

### ISSUE THREAD

**Issue by bmeyer71** [theatlantic/django-nested-admin#141] opened 2019-05-22 16:21 UTC
I'm not sure if this is a Django admin issue or to do with nesting inlines.

In my admin, I have a class that has 3 inlines. One of those inlines also has an inline.
```
parent
   child1
   child2
       child2.1
   child3

```
They are using the autocomplete function for lookups.
The new inline (child3) that I have added to the parent has a date widget/field.
If I leave autocomplete enabled for child2.1 I get the following dump in the console.

> MediaOrderConflictWarning: Detected duplicate Media files in an opposite order: ['admin/js/vendor/jquery/jquery.js', 'admin/js/jquery.init.js', 'admin/js/core.js', 'admin/js/admin/RelatedObjectLookups.js', 'admin/js/actions.js', 'admin/js/urlify.js', 'admin/js/prepopulate.js', 'admin/js/vendor/xregexp/xregexp.js'], [], [], [], [], [], ['admin/js/calendar.js', 'admin/js/admin/DateTimeShortcuts.js'], [], ['admin/js/calendar.js', 'admin/js/admin/DateTimeShortcuts.js'], [], ['admin/js/vendor/jquery/jquery.js', '/nested_admin/server-data.js', 'admin/js/jquery.init.js', 'admin/js/inlines.js', 'admin/js/collapse.js', 'nested_admin/dist/nested_admin.min.js'], ['admin/js/vendor/jquery/jquery.js', 'admin/js/calendar.js', '/nested_admin/server-data.js', 'admin/js/vendor/select2/select2.full.js', 'admin/js/admin/DateTimeShortcuts.js', 'admin/js/jquery.init.js', 'admin/js/inlines.js', 'admin/js/autocomplete.js', 'admin/js/collapse.js', 'nested_admin/dist/nested_admin.min.js'], ['admin/js/vendor/jquery/jquery.js', 'admin/js/calendar.js', '/nested_admin/server-data.js', 'admin/js/jquery.init.js', 'admin/js/admin/DateTimeShortcuts.js', 'admin/js/inlines.js', 'admin/js/collapse.js', 'nested_admin/dist/nested_admin.min.js']
>   ), MediaOrderConflictWarning
> 

That prevents the field in child2.1 from working with autocomplete.
If I comment out the autocomplete line for the child2.1 inline the error goes away.
However, that is not the desired result.

It seems to be a conflict or ordering of the media files in the child2.1 inline and at least the date widget media files of the new inline.

Please let me know if there is any more information I can provide.

**Comment by fdintino** [comment] 2020-04-15 14:59
Hi! Could you provide a bit more detail here? What version of django and django-nested-admin are you using? Can you give a pared down example of your admin and models that I might use to try to reproduce the issue?

**Comment by bmeyer71** [comment] 2020-04-23 15:46
Django version currently is 2.2.8 and django-nested-admin was 3.2.4
I've updated to the latest now 3.3.0 and it seems the issue is gone. If it returns, I will re-open this issue.

**Comment by bmeyer71** [comment] 2020-04-23 16:05
actually I was wrong :( the message is still dumped and the autocomplete does not work.

Django version currently is 2.2.8 and django-nested-admin was 3.2.4
I've updated to the latest now 3.3.0 and it seems the issue is still there.
I will try to put an example together and reply.

**Comment by fdintino** [comment] 2020-05-28 14:15
I'm able to replicate this. Still puzzling over it, but I'll hopefully put together a fix soon.

**Comment by fdintino** [comment] 2020-06-01 19:05
I've got a rough draft of a fix for this. It is actually a requirement for getting django-nested-admin working with django 3.1, since they started using a topological sort to merge `Media` instances. This means that we need to be more intentional about declaring js dependencies for `nested_admin.js`. It's a fairly involved patch and needs extra testing to avoid regressions with Django 1.11, so I don't think it will make it into the upcoming 3.3.1 release.

**Comment by renatohr** [comment] 2020-06-02 13:02
I have faced the same issue here, and it is very unpredictable - I did not find a pattern. I have a few django_nested inlines in my entity admin and some of these inlines have DateField pickers. Sometimes when I add a new inline with DateField, I have this Media warning in the Backend and a javascript conflict in the Frontend (autocomplete's select2 is no longer recognized). The conflict happens also with direct children from modeladmin, not only subchildren. 

I'm using:
Django==2.2.6
django-nested-admin==3.3.0

**Comment by fdintino** [comment] 2020-06-03 17:41
@renatohr @bmeyer71 Can you see if the [fix-media-order](https://github.com/theatlantic/django-nested-admin/tree/fix-media-order) branch resolves your issue?

**Comment by David-Yarnell** [comment] 2020-06-03 21:36
I was running nested inlines and was having problems with autocomplete fields also. The fix-media-order branch seemed to fix the issue for me. Thanks

Django==2.2.11
django-nested-admin==3.3.1

**Comment by bmeyer71** [comment] 2020-06-04 12:34
@fdintino Excellent! That seems to have resolved the issue I was seeing. Thank you.

**Closed** 2020-06-10 07:12 UTC
