### ISSUE TITLE
DateTimeField's widget doesn't work

### ISSUE THREAD

**Issue by rafick1983** [theatlantic/django-nested-admin#71] opened 2017-03-20 12:30 UTC
The widget has no proper event listener for click event. When clicking on date icon, the page scrolls up to the beginning. I encountered this bug when the field was located on nested inline.

**Comment by fdintino** [comment] 2017-03-20 12:40
Are you using grappelli? There is a [known bug](https://github.com/theatlantic/django-nested-admin/blob/1f75ba3e0b9edd56fb6e6b27e58e83c86e8c8441/nested_admin/tests/admin_widgets/tests.py#L261-L266) with the datetime widget and grappelli. If I can spare some time I can look into fixing it.

**Comment by rafick1983** [comment] 2017-03-20 12:50
No, standard admin.
Django==1.10.6
django-nested-admin==3.0.16

**Comment by fdintino** [comment] 2017-03-20 13:00
Interesting. Could you do me a favor to debug? Here are the steps to run the tests with your environment:

1) Activate your virtualenv
2) Reinstall django-nested-admin from source
    * `pip uninstall django-nested-admin`
    * `pip install -e git+https://github.com/theatlantic/django-nested-admin.git@v3.0.16#egg=django-nested-admin`
3) Install test dependencies:
    * `pip install selenium django-admin-testutils dj-database-url`
4) Make sure phantomjs or chromedriver is installed on your system
5) `cd src/django-nested-admin`
6) Run the test
    * `python runtests.py TestAdminWidgets.test_add_two_deep_datetime`
    * or, for chromedriver, add `--selenium=chrome` to the runtests.py arguments

**Comment by rafick1983** [comment] 2017-03-20 13:24
Using Python version 2.7.12 from /home/alex/.virtualenvs/nrds/bin/python
Using Django version 1.10.6 from /home/alex/.virtualenvs/nrds/local/lib/python2.7/site-packages/django
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_add_two_deep_datetime (nested_admin.tests.admin_widgets.tests.TestAdminWidgets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/nrds/src/django-nested-admin/nested_admin/tests/admin_widgets/tests.py", line 263, in test_add_two_deep_datetime
    self.load_admin()
  File "/home/alex/.virtualenvs/nrds/src/django-nested-admin/nested_admin/tests/base.py", line 274, in load_admin
    self.admin_login("super", "secret", url)
  File "/home/alex/.virtualenvs/nrds/src/django-nested-admin/nested_admin/tests/base.py", line 184, in admin_login
    self.selenium.add_cookie({'name': k, 'value': v.value, 'path': '/'})
  File "/home/alex/.virtualenvs/nrds/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 673, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/home/alex/.virtualenvs/nrds/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/home/alex/.virtualenvs/nrds/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: {"errorMessage":"Can only set Cookies for the current domain","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"144","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:44533","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"33c73140-0d70-11e7-bf9d-a105e324130d\", \"cookie\": {\"path\": \"/\", \"name\": \"sessionid\", \"value\": \"4fm0b2xeytke2gtb11dchjw9j7s8jkms\"}}","url":"/cookie","urlParsed":{"anchor":"","query":"","file":"cookie","directory":"/","path":"/cookie","relative":"/cookie","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/cookie","queryKey":{},"chunks":["cookie"]},"urlOriginal":"/session/33c73140-0d70-11e7-bf9d-a105e324130d/cookie"}}
Screenshot: available via screen


----------------------------------------------------------------------
Ran 1 test in 5.154s

FAILED (errors=1)
Destroying test database for alias 'default'...

**Comment by fdintino** [comment] 2017-03-20 13:32
Oh, looks like you encountered a phantomjs bug ([see here](https://github.com/ariya/phantomjs/issues/14047)). It's fixed in [d038837](https://github.com/ariya/phantomjs/commit/d0388371cfda166d97165c1b68182857b954cc83) but annoyingly hasn't made it into a release yet. Judging by the paths in your error output it looks like you're running linux, in which case you can use [this binary](https://github.com/nkovacs/selenium-standalone-phantomjs/tree/62f2a2a56ddbce1c13218aabe60f516afdeffdd8) of phantomjs 2.1.1 with the patch included built for x86_64 linux.

**Comment by rafick1983** [comment] 2017-03-20 13:41
The test has passed :-/

**Comment by fdintino** [comment] 2017-03-20 13:55
Hmm, can you think of anything that might be different between your setup and the test environment, or between the bug you've encountered and the tests in the [admin_widgets tests](https://github.com/theatlantic/django-nested-admin/blob/1f75ba3e0b9edd56fb6e6b27e58e83c86e8c8441/nested_admin/tests/admin_widgets/tests.py)? Here are the various scenarios you will want to test to see if it's a general issue or it's a use case that doesn't have test coverage:

- Does it happen on datetime widgets of inlines that have already been saved, or only on newly-added inlines?
- Does it occur for blank "extra" inlines?
- Do you have drag-and-drop sorting enabled, or not?
- Are you using Django's new "collapse" functionality on your inlines?
- Are these stacked inlines or tabular inlines? Does the bug persist if you change the inline type?
- Is this a generic inline?

Examples of things that could potentially cause the issue while the test would still pass:

- Using a custom change_list template or base admin template
- Having a version of jQuery different than the one bundled with django
- Any `INSTALLED_APPS` that might be overriding jQuery or that are causing javascript errors which stop javascript execution before the cropduster javascript that attaches events. Check the browser's console log to look for anything unusual.

Other information that might help me debug:

- What is the element id of the input for the datetime widget that isn't working
- If you temporarily replace the nested admin classes in your admin.py with the standard `django.contrib.admin` ones, and you have the datetime widget on the top-level inline, does it work?

**Comment by rafick1983** [comment] 2017-03-20 14:19
It woks only if extra attr of the inline is >= 1. It's not working with zero value.

**Comment by rafick1983** [comment] 2017-03-20 14:39
It also doesn't work with new fieldsets created by clicking on 'add another ...' link.

**Comment by fdintino** [comment] 2017-03-21 02:42
I'm afraid I can't reproduce the issue, in both of the cases you listed above. Is there any chance you are overriding the `@property def media` on your `ModelAdmin`, or that you are using a non-standard static file plugin? If you view source in your admin, the `<head>` tag should look something like:

```html
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>
<link href="/static/nested_admin/dist/nested_admin.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.min.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.min.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.min.js"></script>
<script type="text/javascript" src="/static/admin/js/inlines.min.js"></script>
<script type="text/javascript" src="/static/admin/js/SelectBox.js"></script>
<script type="text/javascript" src="/static/admin/js/SelectFilter2.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
<script type="text/javascript" src="/_nesting/server-data.js"></script>
<script type="text/javascript" src="/static/nested_admin/dist/nested_admin.js"></script>
```

If `/static/admin/js/admin/DateTimeShortcuts.js` is not among the script tags then something is interfering with the widget media getting collected into `NestedModelAdmin.media`

**Comment by namlook** [comment] 2017-04-11 08:50
I have the same issue : the date widget doesn't work on the newly added fieldset. No grappelli, just Django==1.10.3 and django-nested-admin==3.0.12

**Comment by namlook** [comment] 2017-04-11 08:55
I precise that it doesn't work with NestedStackedInline nether with NestedTabularInline

**Comment by fdintino** [comment] 2017-04-11 12:19
Could you share a paired down example of your models.py and admin.py so that I can try to reproduce?

**Comment by namlook** [comment] 2017-04-12 09:28
Thanks for your concern. I don't have the time to do it yet but I will as soon as I can.

**Comment by mp3il** [comment] 2017-05-11 08:17
I'm having the same problem, using django-suit.

Trying to dig deeper to find out when it does work and when not.

For example: when I'm opening another date time picker, and then try to open the datetime picker inside a nested - it works, but if i click 'add new' and then try to use the date picker it won't work. and again, if i will open another existing row and use the calender there, it will work.

**Comment by davidkrcil** [comment] 2017-05-31 19:09
I am having the some problem: nested_admin.NestedTabularInline does not show the calendar icon. 

I am using Django-suit. When I disable it - it starts to work everywhere.

For a testing I added some DateField to a top level model which is registered via NestedModelAdmin and there it works with Django suit enabled perfectly. 

I changed nested_admin.NestedTabularInline to nested_admin.NestedStackedInline for the model where it does not work and it is ok now. 

The problem is in combination of Django suit and nested_admin.NestedTabularInline for me.

//Last version of all installed

**Comment by kjagiello** [comment] 2017-10-25 17:53
@mp3il Actually, according to the debugger, the function is actually called, but seems to not do anything, for some unknown reason. I could confirm it by try adding a new inline and then run `DJNesting.DjangoInlines.reinitDateTimeShortCuts();`. It didn't have any effect.

**Comment by kjagiello** [comment] 2017-10-25 20:21
The issue in my case was the order of scripts. Django nested admin has somehow ended up before the date widget.

```html
<script type="text/javascript" src="/_nested_admin/server-data.js"></script>
<script type="text/javascript" src="/static/nested_admin/dist/nested_admin.min.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
```

**Comment by Dieterdde** [comment] 2018-05-29 09:03
Same issue here, django 1.11.3 and django-nested-admin 3.0.21

When you add a new nested inline with "Add another<model object name>" even though the calendar icon and today link display correctly, clicking on them just scrolls you to the top of the page. It seems the events aren't being attached to these html elements when adding a new blank nested inline.

It makes django-nested-admin completely useless to us right now, which is such a pity as it works well other than that.

This is what's in the <head> of the admin page:


<head>
--
  | <title>xxx</title>
  | <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
  | <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
  |  
  |  
  | <script type="text/javascript" src="/admin/jsi18n/"></script>
  | <link href="/static/autocomplete_light/vendor/select2/dist/css/select2.css" type="text/css" media="all" rel="stylesheet" />
  | <link href="/static/autocomplete_light/select2.css" type="text/css" media="all" rel="stylesheet" />
  | <link href="/static/nested_admin/dist/nested_admin.min.css" type="text/css" media="all" rel="stylesheet" />
  | <script type="text/javascript" src="/static/admin/js/core.js"></script>
  | <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
  | <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
  | <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
  | <script type="text/javascript" src="/static/admin/js/actions.js"></script>
  | <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
  | <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
  | <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
  | <script type="text/javascript" src="/static/autocomplete_light/jquery.init.js"></script>
  | <script type="text/javascript" src="/static/autocomplete_light/autocomplete.init.js"></script>
  | <script type="text/javascript" src="/static/autocomplete_light/vendor/select2/dist/js/select2.full.js"></script>
  | <script type="text/javascript" src="/static/autocomplete_light/select2.js"></script>
  | <script type="text/javascript" src="/static/admin/js/inlines.js"></script>
  | <script type="text/javascript" src="/_nested_admin/server-data.js"></script>
  | <script type="text/javascript" src="/static/nested_admin/dist/nested_admin.min.js"></script>
  | <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
  | <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
  |  
  | <meta name="robots" content="NONE,NOARCHIVE" />
  | </head>

**Comment by fdintino** [comment] 2018-05-29 14:15
@Dieterdde Your note about the issue appearing when the last inline formset has the widget is very helpful, it will allow me to create a test case. Thanks for the detailed description!

**Comment by leibowitz** [comment] 2018-08-12 10:04
Having the same issue under the latest django 1.x. The order of the scripts are not preserved, and the `DateTimeShortcuts.js` appears last.

As https://github.com/theatlantic/django-nested-admin/issues/71#issuecomment-339458712 pointed out, this is fixed in django 2.x, as the order of the js scripts is respected.

**Comment by fdintino** [comment] 2018-08-12 18:09
Oh, I had somehow missed that comment. That suggests a relatively easy fix. I'll work on it today.

**Closed** 2018-08-13 12:13 UTC
Labels: question

**Comment by jlugao** [comment] 2018-08-30 16:35
is there a workaround for the bug mentioned by @fdintino on grappelli?

**Comment by fdintino** [comment] 2018-08-31 05:49
@jlugao there is not, but it can be fixed. I worked on it this evening and have committed a fix to the [develop](https://github.com/theatlantic/django-nested-admin/compare/develop) branch (see 67809e5) and will include it in the 3.1.2 release.

**Comment by jlugao** [comment] 2018-08-31 16:47
great! I just tested (and kinda pointed my production env towards this branch). Looking forward for the next releade =)
Thank you very much
